In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("data/powerstations.csv")
df['size_mw'] = df['size_kw']/1000
df.head()

,name,state,postcode,size_kw,accreditation_date,latitude,longitude,aemo_registered,aemo_duid,aemo_registration_type,url,size_mw
0,Ausgrid Muswellbrook,NSW,2009,199.9,2019-07-22,-33.868393,151.193787,No,NaN,NaN,NaN,0.1999
1,BUPA Templestowe,VIC,3020,199.0,2018-04-17,-37.809478,144.818624,No,NaN,NaN,NaN,0.1990
2,Faulding Street Solar,ACT,2609,347.6,2016-09-28,-35.335175,149.168021,No,NaN,NaN,NaN,0.3476
3,Beverage Drive,VIC,3043,146.6,2019-07-31,-37.718861,144.863592,No,NaN,NaN,NaN,0.1466
4,Merredin Solar,WA,6415,131965.1,2020-06-01,-31.543090,118.222469,Yes,NaN,WA-registered,NaN,131.9651

In [8]:
per_state = df.groupby("state").size_mw.agg("sum")
per_state
per_state.to_csv("data/per_state_capacity.csv")